[package]
name = "rust_perlin"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.20.0"
rand = "0.8.5"
rand_distr = "0.4.3"
